export const dataActors = {
	name: "Atores do Semiárido",
	id: "Atores do Semiárido",
	shortName: "Atores",
	color: "#ffffff",
	donutData: {},
	children: [
		{
			name: "Instituição de Ensino Superior",
			id: "Instituição de Ensino Superior",
			shortName: "Instituições de Ensino Superior",
			color: "#4C9E59",
			donutData: {},
			children: [
				{
					name: "Institutos Federais",
					id: "IF",
					shortName: "Institutos Federais",
					color: "#4C9E59",
					donutData: {},
					value: 25,
				},
				{
					name: "Universidades Federais",
					id: "UF",
					shortName: "Universidades Federais",
					color: "#4C9E59",
					value: 25,
				},
				{
					name: "Universidades Estaduais",
					id: "UE",
					shortName: "Universidades Estaduais",
					color: "#4C9E59",
					donutData: {},
					value: 25,
				},
				{
					name: "Universidades Privadas",
					id: "Privada",
					shortName: "Universidades Privadas",
					color: "#4C9E59",
					donutData: {},
					value: 25,
				},
			],
		},
		{
			name: "Institutos de Pesquisa",
			id: "Institutos de Pesquisa",
			shortName: "Institutos de Pesquisa",
			color: "#3F90B2",
			donutData: {},
			children: [
				{
					name: "Governamental",
					id: "Governamental",
					shortName: "Intitutos governamentais",
					color: "#3F90B2",
					donutData: {},
					value: 50,
				},
				{
					name: "Privado",
					shortName: "Intitutos privados",
					id: "Privada",
					color: "#3F90B2",
					donutData: {},
					value: 50,
				},
			],
		},

		{
			name: "Orgão de fomento",
			id: "Orgão de fomento",
			shortName: "Orgãos de fomento",
			color: "#712773",
			donutData: {},
			children: [
				{
					name: "Nacional",
					id: "Nacional",
					shortName: "Orgãos nacionais",
					color: "#712773",
					donutData: {},
					value: 50,
				},
				{
					name: "Internacional",
					id: "Internacional",
					shortName: "Orgãos internacionais",
					color: "#712773",
					donutData: {},
					value: 50,
				},
			],
		},
		{
			name: "Organizações da Sociedade Civil",
			id: "OSC",
			shortName: "Organizações da Sociedade Civil",
			color: "#f7473b",
			donutData: {},
			children: [
				{
					name: "Atividades de associações de defesa de direitos sociais",
					id: "Atividades de associações de defesa de direitos sociais",
					shortName: "Atividades de associações",
					color: "#f7473b",
					donutData: {},
					value: 100,
				},
			],
		},
		{
			name: "Governamental",
			id: "Governamental",
			shortName: "Entidades governamentais",
			color: "#B08A03",
			donutData: {},
			children: [
				{
					name: "Estadual",
					id: "Estadual",
					shortName: "Entidades estaduais",
					color: "#B08A03",
					donutData: {},
					value: 50,
				},
				{
					name: "Nacional",
					id: "Nacional",
					shortName: "Entidades nacionais",

					color: "#B08A03",
					donutData: {},
					value: 50,
				},
			],
		},
	],
};
